algorithms: 'bfs'

train_lengths: ['4', '7', '11', '13', '16']
length_needle: -8
seed: 42

random_pos: true
enforce_permutations: true
enforce_pred_as_input: true

batch_size: 32
chunked_training: false
chunk_length: 16
train_steps: 100000
eval_every: 50
test_every: 500

hidden_size: 128
nb_heads: 1
nb_msg_passing_steps: 1
learning_rate: 0.001
grad_clip_max_norm: 1.0
dropout_prob: 0.0
hint_teacher_forcing: 0.0

hint_mode: 'encoded_decoded'
hint_repred_mode: 'soft'

use_ln: true
use_lstm: false
nb_triplet_fts: 8

encoder_init: 'xavier_on_scalars'
processor_type: 'triplet_gmpnn'
mpnn_processor_aggregator: 'max'

checkpoint_path: '/tmp/CLRS30'
dataset_path: '/tmp/CLRS30'
freeze_processor: false